const SHOP_KEY = 'SHOP_KEY';
const RECENT_LOGINS_KEY = 'RECENT_LOGINS_KEY';
const INITIAL_SETTINGS_COMPLETED_KEY = 'INITIAL_SETTINGS_COMPLETED_KEY';
const MAIN_FOLDER_KEY = 'MAIN_FOLDER_KEY';
const MAXIMIZE_SCREEN_KEY = 'MAXIMIZE_SCREEN_KEY';
const TOKEN_KEY = 'TOKEN_KEY';
const THEME_KEY = 'THEME_KEY';

export {
  SHOP_KEY,
  RECENT_LOGINS_KEY,
  INITIAL_SETTINGS_COMPLETED_KEY,
  MAIN_FOLDER_KEY,
  MAXIMIZE_SCREEN_KEY,
  TOKEN_KEY,
  THEME_KEY
};
