const SHOP_KEY = 'SHOP_KEY';
const RECENT_LOGINS_KEY = 'RECENT_LOGINS_KEY';
const INITIAL_SETTINGS_COMPLETED_KEY = 'INITIAL_SETTINGS_COMPLETED_KEY';
const MAIN_FOLDER_KEY = 'MAIN_FOLDER_KEY';

export {
  SHOP_KEY,
  RECENT_LOGINS_KEY,
  INITIAL_SETTINGS_COMPLETED_KEY,
  MAIN_FOLDER_KEY,
};
