const LOGIN_ROUTE = '/';
const ORDERS_ROUTE = '/ORDERS';
const ORDER_DETAIL_ROUTE = '/ORDER_DETAIL';
const MOYSKLAD_ROUTE = '/MOYSKLAD';
const MOVES_DETAIL_ROUTE = '/MOVES_DETAIL';
const CONTROL_ROUTE = '/CONTROL';
const PROFILE_ROUTE = '/PROFILE';
const SETTINGS_ROUTE = '/SETTINGS';
const TASKS_ROUTE = '/TASKS';
const TASK_DETAIL_ROUTE = '/TASK_DETAIL';
const HELP_ROUTE = '/HELP';
const MESSENGER_ROUTE = '/MESSENGER';

export {
  LOGIN_ROUTE,
  ORDERS_ROUTE,
  ORDER_DETAIL_ROUTE,
  MOYSKLAD_ROUTE,
  MOVES_DETAIL_ROUTE,
  CONTROL_ROUTE,
  PROFILE_ROUTE,
  SETTINGS_ROUTE,
  TASKS_ROUTE,
  TASK_DETAIL_ROUTE,
  HELP_ROUTE,
  MESSENGER_ROUTE,
};
