const LOGIN_ROUTE = '/';
const ORDERS_ROUTE = '/ORDERS';
const ORDER_DETAIL_ROUTE = '/ORDER_DETAIL';
const MOYSKLAD_ROUTE = '/MOYSKLAD';
const MOVES_DETAIL_ROUTE = '/MOVES_DETAIL';
const CONTROL_PANEL_ROUTE = '/CONTROL_PANEL';
const PROFILE_ROUTE = '/PROFILE';
const INITIAL_SETTINGS_ROUTE = '/INITIAL_SETTINGS';
const SETTINGS_ROUTE = '/SETTINGS';

export {
  LOGIN_ROUTE,
  ORDERS_ROUTE,
  ORDER_DETAIL_ROUTE,
  MOYSKLAD_ROUTE,
  MOVES_DETAIL_ROUTE,
  CONTROL_PANEL_ROUTE,
  PROFILE_ROUTE,
  INITIAL_SETTINGS_ROUTE,
  SETTINGS_ROUTE,
};
